services:
  rss-assistant:
    image: ghcr.io/thevops/rss-assistant:latest
    container_name: rss-assistant
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/config.yaml
      - LOG_LEVEL=DEBUG
    volumes:
      - ./config.yaml:/config.yaml:ro
      - ./db:/app/db
